### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by Tobe2d** [owid/co2-data#30]
I would like to know if this dataset is updated and how often get updates?

I saw in the changelog:
April 15, 2022:
Updated primary energy consumption data.
Updated CO2 data to include aggregations for the different country income levels.

However, when I look into the JSON file i cant see anything after 2020. am I missing someghing?

One more question, Is it posible to get live data for CO2 Emissions?

**Comment by pabloarosado** [comment]
Hi @Tobe2d, our CO2 dataset will be updated in less than two weeks. But keep in mind that we use data from different sources and some variables may be more up-to-date than others. Also, given that the dataset has yearly data, it is understandable to not have data on 2022, since the year has not finished yet. We do not provide live data on CO2 emissions.

**Comment by Tobe2d** [comment]
Thanks for the reply @pabloarosado. and thank you to all of you guys behind this great recource for all the efforts to put this togather, this is something everyone should be talking about.

I was planing to use your dataset as part of a website related to climate change​ awareness to show comparisons like year by year and country vs country etc.
But I need to know how much relible are those sources? since you mentioned: You get the data from different sources and some variables may be more up-to-date than others. 

In regards to live data, could you point me into some source providing such data? even if it is paied as this will be very usefull for my needs.
