### ISSUE TITLE
Is there any timeline with regard to the release of 2022 data?

### ISSUE THREAD

**Issue by sz55net** [owid/co2-data#37]

**Comment by pabloarosado** [comment]
Our emissions data relies on the [Global Carbon Budget](https://globalcarbonbudget.org/carbonbudget/), among other datasets. Their latest update was on 2022-11-11 (including data until 2021), so I suppose their next update will be around November 2023 (including data until 2022).
We may update our emissions dataset prior to that because other sources we use have also been updated. But the main data will unfortunately have to wait until the next update by the Global Carbon Budget.
